# Generated by Django 5.2.7 on 2025-10-23 16:03

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("provider", models.CharField(default="stripe", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PAID", "Pagado"),
                            ("FAILED", "Fallido"),
                            ("REFUNDED", "Reembolsado"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
                    models.Index(fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"),
                ],
            },
        ),
    ]
