# Generated by Django 5.2.7 on 2025-10-23 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "plate",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Placa inválida: usa mayúsculas, números y guión (5-10 chars).",
                                regex="^[A-Z0-9\\-]{5,10}$",
                            )
                        ],
                    ),
                ),
                ("make", models.CharField(max_length=50, verbose_name="Marca")),
                ("model", models.CharField(max_length=50, verbose_name="Modelo")),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1980),
                            django.core.validators.MaxValueValidator(2026),
                        ]
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["plate"],
                "indexes": [
                    models.Index(fields=["plate"], name="vehicles_ve_plate_f1ecfa_idx"),
                    models.Index(fields=["owner"], name="vehicles_ve_owner_i_fb6fe6_idx"),
                ],
            },
        ),
    ]
