# Generated by Django 5.2.7 on 2025-10-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("PUSH", "Push")],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=120)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("QUEUED", "En cola"), ("SENT", "Enviada"), ("FAILED", "Fallida")],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
